const express = require('express')
const router = express.Router()
const videoController = require('../controllers/videos')
const authService = require('../service/auth')
const commentController = require('../controllers/comments')
router.use(authService.authenticate)
router.post('/upload', videoController.upload)
router.get('/random', videoController.showRandomVideo)
router.get('/:id', videoController.getVideoById)
router.put('/:id', videoController.updateVideo)
router.delete('/:id', videoController.removeVideo)
router.post('/:videoId/comments', commentController.addComment)
router.get('/:videoId/comments', commentController.getCommentsByVideo)
router.put('/:videoId/comments/:commentId', commentController.editComment)
router.delete('/:videoId/comments/:commentId', commentController.removeComment)
module.exports = router
